Database:
  Cache: "false"
  ConnMaxLifTime: 1h
  Debug: "3"
  Enabled: true
  MaxIdleConns: 10
  MaxOpenConns: 100
  Params: "parseTime=true"
  SSLMode: false
  SlowQueryThreshold: 500ms
  Type: mysql
  Server: host.docker.internal:3306
  Database: "mediax"
  Username: admin
  Password: "lightbear11"
HTTP:
  BodyLimit: 25mb
  CaseSensitive: false
  CompressedFileSuffix: .evo.gz
  Concurrency: 1024
  DisableDefaultContentType: false
  DisableDefaultDate: false
  DisableHeaderNormalizing: false
  DisableKeepalive: false
  ETag: false
  GETOnly: false
  Host: 0.0.0.0
  IdleTimeout: 0
  Immutable: false
  Network: ""
  Port: 8080
  Prefork: false
  ProxyHeader: X-Forwarded-For
  ReadBufferSize: 10mb
  ReadTimeout: 1s
  ReduceMemoryUsage: false
  ServerHeader: EVO
  StrictRouting: false
  UnescapePath: false
  EnablePrintRoutes: false
  WriteBufferSize: 4kb
  WriteTimeout: 5s